export { db } from './client.js'
export { defineTable, getTableDefinitions, getTableDefinition, clearTableDefinitions } from './schema.js'
export { Migrator } from './migrator.js'
export { QueryBuilder } from './query-builder.js'
export * from './types.js'

// Advanced features
export { createRLSManager, createRLSManagerWithTracking } from './rls.js'
export { createTriggerManager } from './triggers.js'
export { createDbFunctionManager } from './functions.js'
export { createSearchManager } from './search.js'
export { createVectorManager } from './vectors.js'
export { createCronManager } from './cron.js'
export { createQueueManager } from './queues.js'
export { createWebhookManager } from './webhooks.js'
export { createBranchManager } from './branching.js'

// Enhanced database features
export { createMigrationManager } from './migrations.js'
export type { MigrationManager, MigrationFile, MigrationRecord, MigrationStatusEntry, SchemaDiff } from './migrations.js'
export { createConnectionPool } from './pool.js'
export type { ConnectionPoolManager, PoolConfig, PoolConnection, PoolStats } from './pool.js'
export { createBackupManager } from './backups.js'
export type { BackupManager, BackupConfig, BackupInfo, WalStatus, ScheduleHandle } from './backups.js'
export { createReplicaManager } from './replicas.js'
export type { ReplicaManager, ReplicaConfig, ReplicaInfo } from './replicas.js'
export { createTypeGenerator } from './typegen.js'
export type { TypeGenerator, ColumnInfo, TableSchema, WatchHandle } from './typegen.js'
